---
- name: Copy dhcp hosts to dnsmasq config
  tags: dhcp_hosts
  ansible.builtin.template:
    src: 65-rocky-router-hosts.conf.j2
    dest: /etc/dnsmasq.d/65-rocky-router-hosts.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart dnsmasq
